tasks:
   - name: installing mysql-server
     ansible.builtin.dnf:
        name: mysql-server
        state: latest

   - name: starting mysql
     ansible.builtin.service:
       name: mysqld
       state: started
       enabled: yes

   - name: installing mysql python dependencies
     ansible.builtin.pip:
       name:
       - PyMySql
       - cryptography
       executable: pip3.9

       
   - name: setting the password
     community.mysql.mysql_info:
       login_user: root
       login_password: "{{ mysql_root_password }}"
       login_host: db.daws-78s.site
       filter: version
     ignore_errors: yes
     register: mysql_connection_output

   - name: print the information
     ansible.builtin.debug:
       msg: "output: {{mysql_connection_output}}"

   - name: setting the username and passsword
     ansible.builtin.command: "mysql_secure_installation --set--root-pass {{ mysql_root_password }}"
     when: mysql_connection_output.failed is true
